### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by AlexGluck**

### CODE REVIEW

**Comment by jenslody** [comment]
Merged into master and any thanks for your contribution.

**Comment by AlexGluck** [comment]
Update please in extensions.gnome.org

**Comment by jenslody** [comment]
Already done (v33), had to be add to LINGUAS-file also, so the make-system knows about the file.

**Comment by AlexGluck** [comment]
Ok, thx. I update extension, work fine. Fedora 26 at xorg

**Pull request merged**
